### ISSUE TITLE
Images not loading in the ethereum whitepaper

### ISSUE THREAD

**Issue by toct92** [ethereum/wiki#97] opened 2016-09-07 05:09 UTC
The images are not loading in the ethereum whitepaper. 
![image](https://cloud.githubusercontent.com/assets/11087174/18300505/46fc3fd4-74e7-11e6-9091-3e102bc8a3a8.png)

And also, when you try to open the images in a new page, it shows: 
![image](https://cloud.githubusercontent.com/assets/11087174/18300518/67ef402e-74e7-11e6-80e0-269f0ee41629.png)

**Comment by mario02423** [comment] 2016-10-04 15:10
Duplicate of https://github.com/ethereum/wiki/issues/85

**Closed** 2018-05-29 09:28 UTC
